### ISSUE TITLE
Panic with prometheus reporter: "tally.internal.counter-cardinality" is not a valid metric name

### ISSUE THREAD

**Issue by vincentdaniel** [uber-go/tally#198]
[This change](https://github.com/uber-go/tally/pull/189) included in release [v4.1.5](https://github.com/uber-go/tally/releases/tag/v4.1.5) introduced new metrics with names that seem not valid metric names for prometheus:

```
panic: descriptor Desc***fqName: "tally.internal.counter-cardinality", help: "tally.internal.counter-cardinality counter", constLabels: ***, variableLabels: [version]*** is invalid: "tally.internal.counter-cardinality" is not a valid metric name

goroutine 8 [running]:
github.com/uber-go/tally/v4/prometheus.NewReporter.func1(***0x1ff88a0, 0xc0004804e0***)
	/home/runner/go/pkg/mod/github.com/uber-go/tally/v4@v4.1.5/prometheus/reporter.go:306 +0x76
github.com/uber-go/tally/v4/prometheus.(*reporter).AllocateCounter(0xc0002f8e00, ***0x1d94d48, 0x22***, 0xc000310360)
	/home/runner/go/pkg/mod/github.com/uber-go/tally/v4@v4.1.5/prometheus/reporter.go:366 +0x322
github.com/uber-go/tally/v4.(*scopeRegistry).reportInternalMetrics(0xc000310780)
	/home/runner/go/pkg/mod/github.com/uber-go/tally/v4@v4.1.5/scope_registry.go:262 +0x6b5
github.com/uber-go/tally/v4.(*scopeRegistry).CachedReport(0xc000310780)
	/home/runner/go/pkg/mod/github.com/uber-go/tally/v4@v4.1.5/scope_registry.go:99 +0x91
github.com/uber-go/tally/v4.(*scope).reportRegistry(0xc00028d080)
	/home/runner/go/pkg/mod/github.com/uber-go/tally/v4@v4.1.5/scope.go:262 +0xd5
github.com/uber-go/tally/v4.(*scope).reportLoopRun(0xc00028d080)
	/home/runner/go/pkg/mod/github.com/uber-go/tally/v4@v4.1.5/scope.go:254 +0x59
github.com/uber-go/tally/v4.(*scope).reportLoop(0xc00028d080, 0x0?)
	/home/runner/go/pkg/mod/github.com/uber-go/tally/v4@v4.1.5/scope.go:242 +0xbb
github.com/uber-go/tally/v4.newRootScope.func1()
	/home/runner/go/pkg/mod/github.com/uber-go/tally/v4@v4.1.5/scope.go:182 +0x85
created by github.com/uber-go/tally/v4.newRootScope
	/home/runner/go/pkg/mod/github.com/uber-go/tally/v4@v4.1.5/scope.go:180 +0xc17
```

**Comment by ptxmac** [comment]
This has been reintroduced in v4.1.11
